version: "2"
linters:
  default: all
  disable:
    - depguard
    - wsl
    - funlen
    - revive
    - ireturn
  enable:
    - wsl_v5
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
