services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: dbq_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 100M
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
